use_frameworks!

platform :ios, '9.0'

target 'swift-app-update-checker_Example' do
  pod 'swift-app-update-checker', :path => '../'

  target 'swift-app-update-checker_Tests' do
    inherit! :search_paths

    
  end
end
